### PR TITLE
TAL-125 Create a Maven artifact containing the javadocset command

### PR DESCRIPTION
**Pull request by datalogics-kam**
For Mac use only.

Eases the requirement to have javadocset installed on one's machine.

### CODE REVIEW

**Comment by datalogics-robl** [comment]
@datalogics-kam Any suggestions on how to test this?

**Comment by datalogics-kam** [comment]
You can try building it and seeing if you get a zip with the binary in it. It's already installed in the repo for the other PRs to use.

**Comment by datalogics-robl** [comment]
I don't have write access to this repo, so I'm blocked from merging the PR.

**Comment by datalogics-kam** [comment]
Whoops! Try it now.

**Pull request merged**
